site_name: HARM CORP
site_url: https://harmcorp.github.io
theme:
  name: material
  icon:
    tag:
      rabbitmq: simple/rabbitmq

plugins:
  - search
  - blog
  - tags

nav:
  # - Home: index.md
  - Blog:
    - blog/index.md
    - Tags: blog/tags.md

extra:
  tags:
    Compatibility: compat
    rabbitmq: rabbitmq
